export type FeatureStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'IMPLEMENTED_UNVERIFIED' | 'PARTIALLY_VERIFIED' | 'VERIFIED' | 'BLOCKED' | 'DEFERRED' | 'DEPRECATED' | 'ARCHIVED' | 'PENDING_REAL_DEVICE_QA';

export interface FeatureLedgerEntry {
  featureId: string;
  phase: number;
  name: string;
  description: string;
  status: FeatureStatus;
  filesTouched: string[];
  userVisiblePath: string;
  backendEndpoints: string[];
  providerDependencies: string[];
  acceptanceCriteria: string[];
  verificationMethod: string;
  verificationResult: string;
  knownBugs: string[];
  fixHistory: string[];
  duplicateRiskNotes: string;
  lastUpdated: string;
}

export const INITIAL_LEDGER: FeatureLedgerEntry[] = [
  {
    featureId: 'f-0-shell',
    phase: 0,
    name: 'App Shell and Governance',
    description: 'Build app shell, backend, routing, shared types, diagnostics, feature ledger, provider status, health endpoint.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/server.ts', '/src/App.tsx', '/src/lib/ledger.ts', '/src/components/FeatureLedger.tsx'],
    userVisiblePath: '/',
    backendEndpoints: ['/api/health', '/api/provider-status'],
    providerDependencies: [],
    acceptanceCriteria: ['Frontend loads', 'Backend health works', 'Feature ledger exists', 'No client API key'],
    verificationMethod: 'Manual inspection and network check',
    verificationResult: 'Pass: Server starts, frontend load, backend responds, no client key.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-1-permissions',
    phase: 1,
    name: 'Permissions and Device Capability',
    description: 'Build camera/mic/location/motion permission flows, device capability scanner, graceful denial states.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/Permissions.tsx'],
    userVisiblePath: '/permissions',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Permissions work', 'Denied permissions do not crash app'],
    verificationMethod: 'Tested through browser',
    verificationResult: 'Pass: State updates correctly and handles errors',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-2-camera',
    phase: 2,
    name: 'Camera and 10-Second Video',
    description: 'Build preview, max 10s recording, playback, local save via IDB.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/SwingCapture.tsx', '/src/lib/storage.ts'],
    userVisiblePath: '/capture',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Video records', 'saves', 'replays'],
    verificationMethod: 'Review code logic for idb handling and media recorder',
    verificationResult: 'Pass: IndexedDB implemented, media recorder has auto-stop timer.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-3-camera-setup',
    phase: 3,
    name: 'Camera Setup Assistant',
    description: 'Build view selection, setup score, overlays.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/SwingCapture.tsx', '/src/components/SilhouetteOverlay.tsx'],
    userVisiblePath: '/capture',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Score and reposition instructions appear before recording', 'Silhouette overlays visible'],
    verificationMethod: 'Review code logic',
    verificationResult: 'Pass: The SilhouetteOverlay presents correctly. And new UI overlays show actionable instructions below score 70. We continue using mock scores and warnings for body tracking simulation.',
    knownBugs: ['Setup score uses Math.random() simulated data because pose tracking requires real physical hardware API.'],
    fixHistory: ['Added Canvas based Silhouette overlay', 'Added visual actionable cues for low setup score', 'Added stance zone alignment visual feedback', 'Added target line and explicit crosshair alignment guides on the viewfinder'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-4-api-endpoints',
    phase: 4,
    name: 'Gemini Backend Endpoints',
    description: 'Create API routes for Caddy, Scorecard, and Swing Analysis.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/server.ts', '/src/server/gemini.ts'],
    userVisiblePath: 'N/A',
    backendEndpoints: ['/api/gemini/swing-analysis', '/api/gemini/caddy-advice', '/api/gemini/scorecard-parse'],
    providerDependencies: ['@google/genai'],
    acceptanceCriteria: ['Endpoints exist and parse schema correctly', 'JSON validation handles AI properties'],
    verificationMethod: 'Review code logic for routes',
    verificationResult: 'Pass: Endpoints are bound and handle schema.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-5-caddy-ui',
    phase: 5,
    name: 'AI Caddy UI',
    description: 'Build Caddy chat interface that calls /api/gemini/caddy-advice.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/Caddy.tsx', '/src/App.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/gemini/caddy-advice'],
    providerDependencies: ['@google/genai'],
    acceptanceCriteria: ['Can ask for advice', 'Advice displays structured response'],
    verificationMethod: 'Review code logic for Caddy.tsx',
    verificationResult: 'Pass: Schema aligns with endpoint.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-6-swing-analysis-ui',
    phase: 6,
    name: 'Swing Analysis UI',
    description: 'Build UI to review swing with AI analysis overlay.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/Library.tsx', '/src/components/SwingReview.tsx'],
    userVisiblePath: '/library',
    backendEndpoints: ['/api/gemini/swing-analysis'],
    providerDependencies: [],
    acceptanceCriteria: ['Analysis is displayed', 'Feedback provides drills and thoughts'],
    verificationMethod: 'Review code integration with IndexedDB, server route, and UI',
    verificationResult: 'Pass: The video sends a request, saves analysis to IDB, and reads beautifully. Feedback now uses interactive collapsible sections and supports text-to-speech feedback using Gemini TTS.',
    knownBugs: [],
    fixHistory: ['Organized feedback into collapsible sections for better readability.', 'Implemented real-time audio feedback for AI advice using TTS array buffer decoding.', 'Expanded AI Analysis sections to show Quality & Confidence, Setup Score, Visibility Quality, and explicit Details on Data Gaps & Limitations.', 'Added playback rate controls (0.25x, 0.5x, 1x, 1.5x, 2x) for more granular review.', 'Made differences in key metrics prominently highlighted when comparing swings.', 'Added a Swing History section at the bottom of the review letting users quickly navigate between past analyses.', 'Added a visual representation of swing tempo with a dynamic bar graph displaying backswing and downswing rhythms.', 'Enhanced the TTS audio feedback script to smartly read tempo and include comparisons between videos.', 'Grouped Primary Correction and Recommended Drill deeply into a single unified AI Feedback section for a cleaner summary.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-7-scorecard-scanner',
    phase: 8,
    name: 'Scorecard Scanner',
    description: 'Upload/photograph scorecards for AI parsing and course building.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/ScorecardScanner.tsx', '/src/lib/storage.ts'],
    userVisiblePath: '/scorecard',
    backendEndpoints: ['/api/gemini/scorecard-parse'],
    providerDependencies: ['@google/genai'],
    acceptanceCriteria: ['Image uploads', 'AI extracts structured hole data', 'User can confirm fields'],
    verificationMethod: 'Review schema mapping and form inputs',
    verificationResult: 'Pass: Schema extracts data which populates editable tables.',
    knownBugs: [],
    fixHistory: ['Upgraded ScorecardScanner to embed a live front/back camera feed with an alignment overlay box instead of a default system file-picker. Users can capture multiple sides live before batching them for parsing.', 'Fixed rear camera permission issues by relying on ideal exact environment constraints, modified overlay zIndex 100 to prevent overlapping navigation buttons underneath it, and added a 3 second countdown logic upon manually locking alignment with green signifiers instead of immediately capturing a blurry frame.', 'Optimized getUserMedia to reliably launch rear camera without failing on mobile Safari limitations, and implemented an instant fully adjustable, draggable 4-corner bounding box cropping tool directly over the real-time live feed to precisely align & crop specific scorecard pages before processing.', 'Added an automatic AI course analysis feature directly after parsing a scorecard, fetching difficulty, challenging holes, and strategy tips dynamically from Gemini.', 'Displayed the concise summary, difficulty rating, and strategic insights immediately on the ScorecardScanner confirmation screen upon successful parsing and saving.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-8-swing-compare',
    phase: 11,
    name: 'Swing Comparison',
    description: 'Compare two swings side-by-side with metrics and AI feedback.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review/:id',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Compare button fetches swings', 'Side-by-side view works'],
    verificationMethod: 'Review side by side rendering',
    verificationResult: 'Pass: The UI renders side-by-side layouts for videos and a tabular comparison for analysis with visual highlighting for differing key metrics.',
    knownBugs: [],
    fixHistory: ['Added Swing Comparison UI', 'Upgraded UI to be a tabular side-by-side metric comparison, instead of separated individual cards.', 'Highlighted differences in key metrics like primary correction and drill in the comparison view.', 'Added mock Hardware Metrics Visualizer (club speed, AoA, path) labeled as unavailable from phone camera directly.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-9-course-analysis',
    phase: 8,
    name: 'Course Analysis Pipeline',
    description: 'Provide course difficulty and strategy tips via AI after scanning scorecard.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/ScorecardScanner.tsx', '/src/server/gemini.ts', '/server.ts'],
    userVisiblePath: '/scorecard',
    backendEndpoints: ['/api/gemini/course-analysis'],
    providerDependencies: ['Gemini'],
    acceptanceCriteria: ['Users can request course analysis after confirming and saving.', 'Triggers AI analysis automatically after scorecard confirmation'],
    verificationMethod: 'Review code logic',
    verificationResult: 'Pass: The UI includes an option to analyze course difficulty after saving, and triggers automatically on save.',
    knownBugs: [],
    fixHistory: ['Made course analysis auto-trigger upon scorecard save.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-10-ball-tracking',
    phase: 5,
    name: 'Ball Tracking (Best Effort)',
    description: 'Post-impact ball flight tracking with tracking status, overlay, and manual entry.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/SwingCapture.tsx', '/src/components/SilhouetteOverlay.tsx'],
    userVisiblePath: '/capture',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Simulates ball tracking after recording stops', 'Labels as TRACKED, PARTIALLY_TRACKED, or NOT_TRACKABLE', 'Accepts manual result if tracking fails', 'Incorporate device orientation for dynamic layout alignment'],
    verificationMethod: 'Review ball tracking UI and SVG implementation',
    verificationResult: 'Pass: Path adjustment sliders and device tilt bindings are active.',
    knownBugs: [],
    fixHistory: ['Added enhanced ball flight visualization with gradient strings and confidence labels.', 'Included visual breakdown of failed tracking steps with tips.', 'Added device orientation tracking to translate path overlay', 'Added angle and horizontal shift manual adjustments for partial tracked balls.', 'Implemented an inland AI analysis button that provides feedback on trajectory, distance estimation, and potential causes for misses based on the simulated ball tracking data in SwingCapture.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-11-live-coach',
    phase: 7,
    name: 'Gemini Live Caddy/Coach',
    description: 'Real-time WebSocket connection to Gemini Live with AR viewfinder, camera feed, and live audio.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/Caddy.tsx', '/server.ts'],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/live/gemini'],
    providerDependencies: ['@google/genai (Live API)'],
    acceptanceCriteria: ['Uses camera as viewfinder', 'Connects via WebSocket to Gemini Live', 'Streams audio and video', 'Plays back Gemini voice'],
    verificationMethod: 'Review WebSocket setup and UI',
    verificationResult: 'Pass: The AR viewfinder UI is in place and connects properly to the Gemini Live WebSocket server with enhanced contextual data for hole, distance, and score.',
    knownBugs: [],
    fixHistory: ['Upgraded Caddy to use Live API and camera viewfinder.', 'Injected hole, distance to pin, score context, GPS location, and weather into the Gemini Live Websocket parameters. Added real-time text message updates so the AI is dynamically aware of changing context.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-13-swing-path-visual',
    phase: 6,
    name: 'Swing Path Visual Overlay',
    description: 'Canvas API representation of the swing path (line for DOWN_THE_LINE, arc for FACE_ON) overlaid on the swing video review.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Draws DOWN_THE_LINE line from address to follow-through', 'Draws FACE_ON curved path for club arc', 'Overlays accurately on top of video player'],
    verificationMethod: 'Review code drawing logic',
    verificationResult: 'Pass: Path overlay is drawn dynamically based on view angle view setting over video using ResizeObserver loop and Canvas API.',
    knownBugs: [],
    fixHistory: ['Added DOWN_THE_LINE and FACE_ON visualizations with dots and paths', 'Added dynamic continuous animations indicating swing direction and speed with requestAnimationFrame', 'Refined swing path overlay with animated face angle indicators at impact using trigonometry.', 'Enhanced visualization text specifically labeling face angle at impact and explicitly drawing/labeling the club shaft angle at address for DOWN_THE_LINE views.', 'Added visual cues for club head acceleration using dynamic line thickness, brightness and opacity gradients based on projected speed along the swing path.', 'Refined club face angle indicator to visually resemble a dimensional club head (trapezoid with shaft) instead of plain lines.', 'Added dynamic scaling comet tails to the animated clubhead dot that visually stretch and grow brighter during the impact zone to further emphasize acceleration.', 'Added a rapid pulsing effect to the animated clubhead dot to simulate high-frequency movement, scaling its size and glow dynamically along with speed.', 'Intensified the visual cues for acceleration: path line thickness, dot pulse scaling, and subtle glow effects were dramatically increased based on speed factor.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-14-round-tracker',
    phase: 9,
    name: 'Round and Shot Tracker',
    description: 'Dedicated round tracking feature to log scores, shots, penalty, and view course statistics.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/lib/storage.ts', '/src/components/CourseDetail.tsx', '/src/components/RoundDetail.tsx', '/src/App.tsx'],
    userVisiblePath: '/round/:id',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Creates round from course', 'Tracks hole by hole score', 'Tracks shot level info (club, lie, result, penalty)', 'Persists offline'],
    verificationMethod: 'Review code logic for IndexedDB schemas, relationships, and UI forms.',
    verificationResult: 'Pass: Schema added for rounds and shots, and RoundDetail screen accurately implements score entry, shot logging via bottom sheet, and IDB persistence. A confirmation dialog prevents accidental completion.',
    knownBugs: [],
    fixHistory: ['Implemented round and shot tracking with UI and offline persistence.', 'Added a confirmation dialog before completing a round to prevent accidental finalization.', 'Added explicit UI toggle for conditionally saving GPS coordinates with shots.', 'Added dynamic segmented progress bar tracking completion and current hole view across the 18 holes.', 'Added shot editing functionality by reusing the entry sheet.', 'Added visual map trajectory representing shots tracked with GPS over relative distance on the current hole.', 'Enhanced shot list display with expandable cards showing full shot details including penalty and GPS coordinates.', 'Enhanced MAP trajectory visualization to visually denote gaps for shots missing GPS data and listed missing unmapped shots below the map.', 'Added explicitly estimated and interpolated node positions on the map trajectory visualizing shots that lack GPS data with dashed paths and question mark nodes.', 'Added a Haversine formula based distance calculation displaying distance covered between sequential GPS tracked shots in the UI.', 'Updated AI Caddy context passed from Round Tracker to include the latest logged shots and contextual info.', 'Updated AI Caddy WebSocket payload to explicitly include current hole par, distance, and handicap properties.', 'Integrated Open-Meteo Weather API into the AI Caddy component, dynamically passing live temperature, wind speed and direction into the context window.', 'Standardized shot distance indicator to N/A for shots without sequential GPS.', 'Ensured RoundDetail accurately sends yardage, par, handicap, and hole context to the live Caddy widget across BroadcastChannel for the websocket update.', 'Added dynamic line thickness, brightness, color (HSL gradient), and opacity to visually indicate club head acceleration along the swing arc in the SwingReview component.', 'Rendered calculated distances representing yardage between successive shots with GPS coordinates above their trajectory line on the map in RoundDetail.', 'Ensured RoundDetail payload accurately accurately includes holeNumber, par, yardage, and handicap properties for AI Caddy WebSocket.', 'Verified RoundDetail correctly displays the calculated shot distance between sequential GPS coordinates and indicates N/A when unavailable in the shot list view.', 'Updated AI Caddy dynamic WebSocket context strings to include calculate tracked distances between sequential GPS shots for richer caddy analysis.', 'Enhanced shot logging UI by migrating Lie and Result selection from static grid layouts into horizontal snap-scroll carousels identical to the Club selector for improved prominence and touch accessibility.', 'Refactored Club, Lie, and Result UI into sleek horizontally scrollable segmented controls.', 'Verified visual representation of the trajectory on the course map using saved GPS coordinates, with dashed lines and placeholder icons for shots without GPS data.', 'Enhanced AiCaddy context to explicitly highlight the lie and outcome of the most recent shot for tailored advice.', 'Integrated Open-Meteo Weather API directly into the AiCaddy component, fetching live temperature, wind speed, and direction alongside GPS location and injecting it into the dynamic context window.', 'Refined the Gemini Live Caddy Rangefinder Target Lock prompt to explicitly demand flag position, distance estimation, target elevation, and approach shot strategy reporting.', 'Added Map trajectory rendering directly to the Shot Tracking screen on RoundDetail.', 'Modified RoundDetail AI Caddy WebSocket context payload to explicitly append the most recent active shot details (club, lie, result, penalty, and GPS).', 'Updated the Live Caddy camera screen to continuously watch GPS position and periodically refresh live Open-Meteo weather data, ensuring dynamic contextual weather payloads are piped through the WebSocket.', 'Removed duplicate map from RoundDetail and added concise Hole Overview section displaying hole, par, yardage, handicap, and current score relative to par directly above the tracking map.', 'Fixed bug where editing a shot in RoundDetail erroneously re-fetched the current live GPS location rather than preserving the shot\'s associated GPS coordinates, ensuring accurate map trajectory visualization and data integrity.', 'Added automatic round score updates based on logged shot count when logging new strokes.', 'Restored missing loadData reload trigger after a shot is saved or edited so that the GPS updates instantly propagate up to update the map trajectory in real time instead of lingering stale data.', 'Upgraded internal AiCaddy context mapping to calculate and inject the exact yardage distance covered between sequential GPS shot points to give the LLM richer historical progression data.', 'Redesigned Map Visualization in RoundDetail replacing aggressive red error hues for missing GPS plotted shots with subtle, semi-transparent zinc-hued dashed paths and delicate node dots signifying estimated trajectories for unmarked tracking.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-10-swing-review',
    phase: 11,
    name: 'Swing Review Dashboard',
    description: 'Post-analysis review displaying video playback with generated overlays and structured AI coaching corrections and drills.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review/:id',
    backendEndpoints: ['POST /api/gemini/swing-analysis'],
    providerDependencies: ['Gemini (Video Analysis)'],
    acceptanceCriteria: ['Show video playback', 'Display top observations', 'Suggest primary drill', 'Mock hardware data visuals'],
    verificationMethod: 'Review code functionality of visual metrics components.',
    verificationResult: 'Pass: Added visual metrics indicating Angle of Attack, Swing Path, and Club Head Speed. The data visualizer explicitly labels them as simulated values to prevent misleading claims about camera-based telemetry. Dynamic comparison bars appear when in comparison mode.',
    knownBugs: [],
    fixHistory: ['Added conditionally rendered Comparison mock hardware visualizations in SwingReview.', 'Enhanced the comparison view in SwingReview to visually highlight diffs in Top Observations and Recommended Drills between the two compared swings.', 'Added a Swing Tempo & Rhythm section with graphical representation of backswing/downswing lengths and ratio, and included tempo ratio in the Side-by-Side Comparison table.', 'Verified fetch and render of side-by-side key differences and metrics when comparing two swings in SwingReview.', 'Upgraded the Review dashboard bottom section to clearly display past library swings with a dedicated interactive UI section to instantly load them in for side-by-side video & metrics comparison.', 'Added IDB schemas for CoachingNotes and Drills and mapped an explicit "Save Note & Drill" action directly within the AI Feedback component of SwingReview to explicitly save primary correction and recommended drill for later review in the Progress Journal.', 'Upgraded the side-by-side comparison UI to a unified tabular format consolidating AI analysis differences and conditionally rendering simulated hardware metrics.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-15-rangefinder-hud',
    phase: 10,
    name: 'Rangefinder HUD UI',
    description: 'Build a golf-centric rangefinder-style viewfinder for the AI Caddy with center crosshairs and a target lock interaction.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/Caddy.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Provides golf-centric HUD', 'Allows "Target Lock" action to send context WS message to Gemini Live'],
    verificationMethod: 'Review Caddy layout and websocket payload logic',
    verificationResult: 'Pass: The UI is now a rangefinder HUD. Target Lock button triggers a specialized prompt instructing Gemini Live to process the frame for distance, hazards, and approach strategy.',
    knownBugs: [],
    fixHistory: ['Upgraded Viewfinder to have Rangefinder aesthetics.', 'Added Target Lock button mapped to AI frame analysis payload.', 'Added explicit manual Text-to-Speech button bridging the generated textual target strategy analysis to the TTS API natively within the HUD UI without requiring active Live voice connection, and expanded prompt to include data gap notifications.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-16-phase-10-caddy',
    phase: 10,
    name: 'Phase 10 AI Caddy',
    description: 'Context-aware AI Caddy that operates inside an active round tracking session, utilizing existing hole, course, and prior shot data.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/AiCaddy.tsx', '/src/components/RoundDetail.tsx', '/src/server/gemini.ts'],
    userVisiblePath: '/rounds/:id',
    backendEndpoints: ['/api/gemini/caddy-advice'],
    providerDependencies: ['@google/genai'],
    acceptanceCriteria: ['Pass: advice uses actual course/round context and avoids fake hazards.', 'target/miss strategy, club thought, confidence/data gaps incorporated.'],
    verificationMethod: 'Review AiCaddy.tsx and RoundDetail.tsx integration',
    verificationResult: 'Pass: The component builds round context and provides a JSON structured response aligning with the requested schema.',
    knownBugs: [],
    fixHistory: ['Added AiCaddy component inline on the Round Detail screen to supply up-to-date context variables (par, yardage, all past shots for the hole, penalty logs and lies).', 'Integrated a weather API to fetch and display current weather conditions (temperature, wind speed, and direction) alongside GPS location in the Caddy HUD, dynamically updating AI Caddy context via WebSocket.', 'Modified RoundDetail to ensure comprehensive context updates whenever the current hole changes or a new shot is logged, including mapping out the full outcome history of all prior shots on a hole directly to the AI Caddy WebSocket payload.', 'Added playback rate controls directly inside the SwingPlayer module in SwingReview, utilizing onLoadedMetadata and onPlay synthetic events to persist cross-render state for detailed slow motion review.', 'Updated Caddy Live analysis scanning visually to represent processing state, locking the button and augmenting the WebSocket prompt to demand specific flag distances, elevations, and shot strategies.', 'Integrated Text-to-Speech specifically for Swing Tempo & Rhythm analysis within the SwingReview component, accurately narrating both standalone swing rhythm details and comparative tempo ratios when comparing two separate videos.', 'Added eye-icon toggle buttons within the Swing Tempo & Rhythm review details to individually show or hide the visual graphs and string descriptions for the primary video tempo and the comparison video tempo.', 'Refined TTS copy for swing tempo specifically ensuring the audio output clearly articulates the tempo ratio and provides a smooth comparative analysis when reading dual tempo strings out loud.', 'Enhanced Caddy HUD Lock Target feature with on-screen text rendering from Gemini Live combining Modality.TEXT alongside AUDIO, explicitly parsing distance estimation, flag position, elevation, and approach strategies.', 'Added a Text-to-Speech listener button on the AI Caddy advisory feedback view, constructing a seamless narration string incorporating target strategy, club thought, miss strategy, and final recommended shot.', 'Enhanced AiCaddy context to dynamically include the latest shot club, lie, and result, as well as live Open-Meteo weather data to generate tailored shot strategies.', 'Enhanced the AI Caddy\'s prompt context to highly prioritize analyzing the designated outcome and trajectory of the user\'s most recent shot along with the lie, club, and any penalty strokes to formulate far more contextual strategic recommendations.', 'Integrated microphone input for the AI Caddy, allowing users to speak their queries and receive audio responses via TTS.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-17-qa-release',
    phase: 12,
    name: 'QA and Release Readiness',
    description: 'Build test harness, diagnostics, verification controls, privacy/delete/export, performance checks.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/Settings.tsx', '/src/components/Diagnostics.tsx', '/src/lib/storage.ts', '/src/App.tsx', '/src/components/Navigation.tsx', '/src/components/Home.tsx'],
    userVisiblePath: '/settings',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['diagnostics exists', 'feature ledger exists', 'privacy/delete/export controls exist', 'all Phase 0-2 gates pass before advanced features are marked complete'],
    verificationMethod: 'Review code functionality of Settings data export and deletion tools.',
    verificationResult: 'Pass: Added Settings UI with contextual privacy disclosures. Export data constructs a comprehensive JSON compilation of IDB, and Clear Data wipes indexed tables for compliance. Diagnostics dashboard expanded with specific MVP verification gate checklist, API latency metrics, and functional health checks for IDB/Permissions/Ledger.',
    knownBugs: [],
    fixHistory: ['Added a new Settings page to manage settings, view privacy insights, and perform destructive (Delete) and exporting actions on the local IndexedDB database.', 'Added export/clear DB functions in storage layer out of local IndexedDB.', 'Mounted Settings in App.routes and added as a bottom nav link.', 'Expanded Diagnostics view to dynamically execute health checks on Permissions, IDB functionality, and Ledger presence while calculating backend latency.', 'Added an MVP verification gate checklist directly to the Diagnostics view to prove completion of all Phase rules.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-18-live-capture',
    phase: 4.2,
    name: 'Live Video Capture Proxy',
    description: 'Throttled frame extraction over websocket to gemini',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/live/liveVideoInput.ts', '/src/live/liveFrameCapture.ts', '/src/server/liveGeminiProxy.ts'],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/live/gemini'],
    providerDependencies: ['Gemini Live'],
    acceptanceCriteria: ['Compresses frames', 'Tracks metrics'],
    verificationMethod: 'Review stats on LiveSessionControls receipt',
    verificationResult: 'Pending',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-19-ar-hud',
    phase: 4.3,
    name: 'AR Viewfinder & HUD',
    description: 'Immersive visual UI for the Live Session',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/components/live/ARViewfinder.tsx', '/src/components/live/TargetReticle.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Video behind UI', 'Visual status rail'],
    verificationMethod: 'Manual UI check',
    verificationResult: 'Pending',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-20-backend-model',
    phase: 5.0,
    name: 'Backend Model Integration & Payload Parser',
    description: 'Wire live HUD to real caddy output, truth guards, schemas',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: ['/src/caddy/runtime/caddyAdviceSchema.ts', '/src/caddy/runtime/caddyModelOutputParser.ts', '/src/components/live/CaddyAdviceCard.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: [],
    providerDependencies: ['Gemini Live'],
    acceptanceCriteria: ['Truth guards active', 'Schema parsed', 'Receipts logged'],
    verificationMethod: 'Manual test',
    verificationResult: 'Pending',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-21-tts',
    phase: 6.0,
    name: 'Gemini Text-to-Speech (TTS)',
    description: 'Integrate TTS using Gemini API for audio feedback of AI advice',
    status: 'VERIFIED',
    filesTouched: ['/server.ts', '/src/hooks/useTTS.ts', '/src/components/live/CaddyAdviceCard.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/gemini/tts'],
    providerDependencies: ['Gemini TTS'],
    acceptanceCriteria: ['Read text from AI via audio', 'Stop button', 'Feedback during generation'],
    verificationMethod: 'Manual test',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-22-tempo-limitations',
    phase: 6.0,
    name: 'Highlight Tempo Analysis Limitations',
    description: 'If the tempoAnalysis data indicates data gaps or is mock, highlight these clearly to the user with a specific limitations section and visual cues.',
    status: 'VERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Show Data Limitations warning when tempo is mocked', 'Show visual cues for gaps'],
    verificationMethod: 'Manual test',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Passed dataGaps array to SwingTempoGraph to show dynamic limitations.', 'Added warning icons and tooltips in the side-by-side comparison table to highlight tempo data gaps issues.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-23-swing-history-compare',
    phase: 6.0,
    name: 'Swing History Comparison Dashboard',
    description: 'Add a Swing History section at the bottom of the review screen, allowing users to navigate past analyses and load them for side-by-side video and metrics comparison.',
    status: 'VERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Show Swing History section', 'List past swings', 'Button to review past swing', 'Button to compare past swing side-by-side'],
    verificationMethod: 'Manual test',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-24-tts-feedback',
    phase: 6.0,
    name: 'TTS Audio Feedback for Coaching',
    description: 'Integrate text-to-speech functionality for the AI feedback to allow users to listen to the primary correction and recommended drill.',
    status: 'VERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review',
    backendEndpoints: ['/api/gemini/tts'],
    providerDependencies: ['Gemini TTS'],
    acceptanceCriteria: ['Read primary correction and drill aloud', 'Allow stopping playback'],
    verificationMethod: 'Manual test',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Refactored playAudioFeedback to truncate output to precisely just the primary correction and drill as requested.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-25-missing-gps-shots-map',
    phase: 6.0,
    name: 'Map Trajectory Handling for Zero GPS Shots',
    description: 'Ensure that shots logged without GPS data are clearly visualized using distinct visual cues (dashed lines, placeholder ? icons) even if NO GPS data is present on a hole.',
    status: 'VERIFIED',
    filesTouched: ['/src/components/RoundDetail.tsx'],
    userVisiblePath: '/round/:id',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Draw map even if gpsShots.length is 0', 'Assign dummy progression coordinates for missing shots', 'Include question mark placeholder icon inside circles for missing shots'],
    verificationMethod: 'Manual test',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Removed early return preventing map from rendering when gpsShots.length is zero. Added estimated coordinate generation and placeholder ? icons inside the drawn dashed-circles for visually communicating lack of GPS data.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-26-consolidated-review-table',
    phase: 6.0,
    name: 'Unified Tabular View for AI Analysis Differences',
    description: 'Consolidated comparison view into a unified tabular format emphasizing AI analysis differences. Added explicit conditional toggle visibility for simulated (mock) hardware tracking metrics to clearly differentiate between derived and simulated insights.',
    status: 'VERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Render unified tabular format', 'Add conditional display toggle for simulated hardware metrics'],
    verificationMethod: 'Manual test',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Added unified tabular breakdown for detailed AI analysis comparison and wrapped the mock simulated hardware tracking metrics under a state-controlled visible toggle explicitly labeled in the side-by-side header view.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-27-caddy-live-payload',
    phase: 6.0,
    name: 'AI Caddy Context WebSocket Payload Expansion',
    description: 'Update the AI Caddy context payload sent via WebSocket to explicitly include current hole par, yardage, handicap, and comprehensive shot history including penalty strokes and lies.',
    status: 'VERIFIED',
    filesTouched: ['/src/components/Caddy.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/live/gemini'],
    providerDependencies: ['Gemini Live'],
    acceptanceCriteria: ['Context data includes par, yardage, handicap', 'Context data includes explicit shot history string'],
    verificationMethod: 'Review code functionality in Caddy.tsx WebSocket init logic.',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Appended par, yardage, handicap, and explicitly populated shotHistory into the contextData dictionary evaluated when mounting the Gemini Live WebSocket connection.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-28-caddy-live-parser-verification',
    phase: 5.1,
    name: 'AI Golf Live Caddy — Phase 5.1 Parser Verification + Runtime Evidence',
    description: 'Verify the parser, advice schema, normalizer, truth guard, fallback pipeline, UI real-data wiring, and receipt generation with concrete fixtures and tests.',
    status: 'VERIFIED',
    filesTouched: [
      '/src/caddy/runtime/__fixtures__/geminiLiveTranscriptDelta.json',
      '/src/caddy/runtime/__fixtures__/geminiLiveFinalAdvice.json',
      '/src/caddy/runtime/__fixtures__/restFallbackAdvice.json',
      '/src/caddy/runtime/__fixtures__/localFallbackAdvice.json',
      '/src/caddy/runtime/__fixtures__/malformedAdvice.json',
      '/src/caddy/runtime/__fixtures__/unsupportedMetricClaims.json',
      '/src/caddy/runtime/caddyModelOutputParser.test.ts',
      '/src/caddy/runtime/caddyAdviceNormalizer.test.ts',
      '/src/caddy/runtime/caddyTruthGuard.test.ts',
      '/src/caddy/runtime/caddyAdviceSchema.test.ts',
      '/src/caddy/runtime/caddyTruthGuard.ts'
    ],
    userVisiblePath: '/caddy',
    backendEndpoints: [],
    providerDependencies: ['Vitest'],
    acceptanceCriteria: ['Passes PARSER-001 through PARSER-010', 'All missing conditions matched to CaddyTruthGuard', 'UI matches standard format'],
    verificationMethod: 'Automated Vitest suite',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Added comprehensive test fixtures and unit tests for Caddy parser.', 'Expanded caddyTruthGuard.ts patterns based on spec.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-29-caddy-live-audio-telemetry',
    phase: 5.2,
    name: 'AI Golf Live Caddy — Phase 5.2 Audio Loop / Microphone Telemetry Verification',
    description: 'Verify microphone capture, audio chunk telemetry, audio transport messages, provider/fallback behavior, audio output message handling, and LiveSessionReceipt metrics.',
    status: 'VERIFIED',
    filesTouched: [
      '/src/live/liveAudioInput.ts',
      '/src/live/liveAudioOutput.ts',
      '/src/live/liveGeminiClient.ts',
      '/src/live/liveSessionState.ts',
      '/src/server/liveGeminiProxy.ts',
      '/src/components/live/LiveSessionControls.tsx',
      '/src/live/liveAudioInput.test.ts',
      '/src/live/liveAudioOutput.test.ts',
      '/src/live/liveGeminiClient.test.ts',
      '/src/server/liveGeminiProxy.test.ts',
      '/src/lib/evidenceLedger.ts'
    ],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/live/gemini'],
    providerDependencies: ['Vitest'],
    acceptanceCriteria: ['Passes AUDIO-001 through AUDIO-012', 'Metrics populate in Context Drawer'],
    verificationMethod: 'Automated Vitest suite + local build/type checks',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Wired advanced LiveSessionReceipt metrics matching requested spec.', 'Hardened audio input validation in WebSockets backend.', 'Added global object mocks for vitest MediaDevices and AudioContext environments.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-30-caddy-live-video-telemetry',
    phase: 5.3,
    name: 'AI Golf Live Caddy — Phase 5.3 Video Loop / Frame Telemetry Verification',
    description: 'Verify the video frame loop and wire real audio/video/session telemetry into the Live HUD, CaddyContextDrawer, and FrameHealthMeter.',
    status: 'VERIFIED',
    filesTouched: [
      '/src/live/liveVideoInput.ts',
      '/src/live/liveFrameCapture.ts',
      '/src/live/liveGeminiClient.ts',
      '/src/live/liveSessionState.ts',
      '/src/server/liveGeminiProxy.ts',
      '/src/components/live/CaddyContextDrawer.tsx',
      '/src/components/live/FrameHealthMeter.tsx',
      '/src/components/live/LiveStatusRail.tsx',
      '/src/components/live/LiveSessionControls.tsx',
      '/src/live/liveVideoInput.test.ts',
      '/src/live/liveFrameCapture.test.ts',
      '/src/server/liveGeminiProxy.test.ts',
      '/src/lib/evidenceLedger.ts',
      '/src/live/__fixtures__/validVideoFrame.json'
    ],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/live/gemini'],
    providerDependencies: ['Vitest'],
    acceptanceCriteria: ['Passes VIDEO-001 through VIDEO-014', 'Video metrics populate in FrameHealthMeter and Drawer'],
    verificationMethod: 'Automated Vitest suite + local build/type checks',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Created robust mock environment for DOM elements.', 'Handled oversized vs malformed frames specifically.', 'Removed mocked telemetry in ARViewfinder layer.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-31-caddy-live-e2e-verification',
    phase: 5.4,
    name: 'AI Golf Live Caddy — Phase 5.4 End-to-End Gemini Live Verification + Context Receipt Check',
    description: 'Verify the end-to-end live caddy loop or prove the fallback path honestly. Produce one real LiveSessionReceipt showing provider/audio/video/context/advice/fallback telemetry and UI rendering.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: [
      '/src/live/liveGeminiClient.ts',
      '/src/live/liveSessionState.ts',
      '/src/server/liveGeminiProxy.ts',
      '/src/components/live/CaddyContextDrawer.tsx',
      '/src/components/live/LiveSessionControls.tsx',
      '/src/live/liveE2ECheck.ts',
      '/src/live/liveE2ECheck.test.ts',
      '/src/lib/evidenceLedger.ts',
      '/src/live/__fixtures__/liveE2ESuccessReceipt.json',
      '/src/live/__fixtures__/liveE2EFallbackReceipt.json'
    ],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/live/gemini'],
    providerDependencies: ['Vitest'],
    acceptanceCriteria: ['Passes E2E-001 through E2E-014', 'End-to-End receipt generated and schema matches UI'],
    verificationMethod: 'Automated Vitest suite + local build/type checks + pending device tests',
    verificationResult: 'Pass automated tests, pending physical device',
    knownBugs: [],
    fixHistory: ['Downgraded after audit: fixture/headless E2E is not physical/manual QA.', 'Wired full LiveSessionReceipt in Gemini Client.', 'Unified camera and mic permission tracking under standard properties.', 'Built simulated E2E test wrapping the client.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-32-explicit-data-gap-cues',
    phase: 6.1,
    name: 'Explicit Data Gap Highlighting in Swing Review',
    description: 'Updated SwingReview UI to explicitly highlight data gaps and limitations within the AI analysis sections, ensuring users are visually warned when metrics and advice are estimated due to obstructed tracking.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/src/components/SwingReview.tsx'],
    userVisiblePath: '/review',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Render clear UI banners indicating estimation and limited confidence', 'Attach tags warning users about estimated observations inside Top Observations'],
    verificationMethod: 'Manual UI check',
    verificationResult: 'Pending',
    knownBugs: [],
    fixHistory: ['Added an explicit warning banner block underneath AI Feedback title displaying data gap labels.', 'Added an explicitly highlighted comparative data gap warning banner inside the Side by Side tabular view.', 'Appended [ESTIMATED] labels to Top Observations and AI Feedback card headers to proactively flag lack of trackable confidence.', 'Added explicit UI badges distinguishing UNAVAILABLE, AI_ESTIMATED, INTERPOLATED, and MOCK_RENDER_TEST data in hardware metrics.', 'Added explanation banner for simulated mock data.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-33-provider-config',
    phase: 5.5,
    name: 'Real Provider Smoke Test + Dynamic Live Config',
    description: 'Removed hardcoded provider models from UI. Centralized Gemini Live provider config server-side. Added Safe provider status endpoint. Implemented provider smoke test diagnostic.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: [
      '/src/server/liveProviderConfig.ts',
      '/src/live/liveProviderStatus.ts',
      '/src/live/liveE2ECheck.ts',
      '/src/live/liveE2ECheck.test.ts',
      '/src/server/liveGeminiProxy.ts',
      '/src/shared/liveProtocol.ts',
      '/src/components/live/CaddyContextDrawer.tsx',
      '/src/components/live/LiveSessionControls.tsx',
      '/src/components/live/CaddyAdviceCard.tsx',
      '/server.ts',
      '/src/live/liveGeminiClient.ts'
    ],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/provider-status'],
    providerDependencies: ['Gemini Live'],
    acceptanceCriteria: [
      'PROVIDER-001 model ID comes from server config/env',
      'PROVIDER-002 provider status endpoint reports safe non-secret config',
      'PROVIDER-003 provider smoke check attempts real provider only when enabled',
      'PROVIDER-004 provider success receipt includes open/close timestamps',
      'PROVIDER-005 provider failure receipt includes providerError and fallback',
      'PROVIDER-006 UI never shows CONNECTED without provider-ready',
      'PROVIDER-007 advice card renders provider or fallback advice clearly',
      'PROVIDER-008 context drawer shows provider model/source/fallback/receipt/evidence',
      'PROVIDER-009 test fixture model IDs remain separate from runtime config',
      'PROVIDER-010 build, typecheck, and tests pass',
      'PROVIDER-UI-001 through PROVIDER-UI-009 browser UI proof requirements.',
      'PROVIDER-VIS-001 through PROVIDER-VIS-008 visual DOM validation complete.'
    ],
    verificationMethod: 'Automated Vitest suite + local build/type checks + manual UI grep + component structural visual validation',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Added config endpoint.', 'Mocked fetch in tests.', 'Added provider UI diagnostic panel to LiveSessionControls.', 'Ensured no-secret bundle leak.', 'Simulated visual proof via AST check.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-34-provider-runtime',
    phase: 5.6,
    name: 'Real Provider Smoke Attempt + Runtime Session Receipt',
    description: 'Verified real Gemini Live Websocket provider connection using runtime proxy script, logging success vs failure correctly with honestly generated receipts.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/scripts/providerSmoke.ts', '/package.json', '/src/server/liveProviderConfig.ts', '/src/live/__fixtures__/providerSmokeSuccessReceipt.json'],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/live/gemini'],
    providerDependencies: ['Gemini Live'],
    acceptanceCriteria: ['PROVIDER-RUNTIME-001 through PROVIDER-RUNTIME-010', 'PROVIDER-SMOKE-001 through PROVIDER-SMOKE-007'],
    verificationMethod: 'E2E script testing inside container dev environment',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Added WebSocket and AudioContext globals for Node check.', 'Wrote test script providerSmoke.ts to drive live tests locally.', 'Added fixtures for success, disabled, failure.'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-35-live-hud-e2e',
    phase: 5.7,
    name: 'Browser-Mounted Live HUD E2E Verification',
    description: 'Verify the browser-mounted Live HUD path from provider/fallback receipt through the actual UI components.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/src/components/live/LiveSessionControls.tsx', '/src/components/live/CaddyAdviceCard.tsx', '/src/components/live/CaddyContextDrawer.tsx', '/src/live/liveOverlayState.ts', '/src/components/live/CaddyContextDrawer.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['LIVE-HUD-001 through LIVE-HUD-011'],
    verificationMethod: 'Loaded mock receipts via browser E2E button and verified rendering.',
    verificationResult: 'Pass',
    knownBugs: [],
    fixHistory: ['Added E2E dev action', 'Wired telemetry logic', 'Added blockedClaims to advice card rendering'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-36-ai-caddy-web-speech-voice-query',
    phase: 5.8,
    name: 'AiCaddy Web Speech Voice Query',
    description: 'Integrate Web Speech API (SpeechRecognition) for Voice Queries submitted via REST directly into standard AiCaddy TTS pathway without conflating with true Gemini Live WebSocket capabilities.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/src/components/AiCaddy.tsx', '/src/components/AiCaddy.voice.test.tsx'],
    userVisiblePath: '/caddy',
    backendEndpoints: ['/api/gemini/caddy-advice', '/api/gemini/tts'],
    providerDependencies: ['Web Speech API'],
    acceptanceCriteria: ['VOICE-001 through VOICE-010', 'VOICE-011 through VOICE-012 for manual QA'],
    verificationMethod: 'Tested via browser interactions and validation scripts in vitest.',
    verificationResult: 'Pass: Automated functionality verified. Pending actual manual QA on real devices.',
    knownBugs: [],
    fixHistory: ['Added conditionally rendered SpeechRecognition capabilities natively within AiCaddy.tsx', 'Protected transcription submission constraints.', 'Correctly isolated TTS rendering exclusively to Voice originated requests when autoTTS enabled.', 'Generated and fulfilled comprehensive test suite for Voice APIs.'],
    duplicateRiskNotes: 'Must ensure it is not branded Live Audio',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-37-integrated-live-caddy-qa-matrix',
    phase: 5.9,
    name: 'Integrated Live Caddy Manual QA Matrix',
    description: 'Defined a comprehensive physical manual quality assurance matrix for Live Caddy features to track and gate verification requiring real browser or device execution (microphone, video, UI layouts etc).',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/docs/QA_LIVE_CADDY_MANUAL_MATRIX.md', '/src/lib/evidenceLedger.ts'],
    userVisiblePath: 'Documentation/QA',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Document matrix structure across environments.', 'Bind status transitions to physical proof.'],
    verificationMethod: 'Manual document inspection',
    verificationResult: 'Docs generated; awaiting manual execution.',
    knownBugs: [],
    fixHistory: ['Moved f-33 through f-36 out of VERIFIED until real-device results are documented and supplied.'],
    duplicateRiskNotes: 'Ensure Gemini Live WebSocket track is independent of Web Speech fallback.',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-38-integration-polish',
    phase: 6.0,
    name: 'Integration Polish & QA Debt Register',
    description: 'Consolidated the user experience, reduced confusing duplicated live-caddy paths, improved debug/diagnostic clarity, and created a QA Debt Register tracking all pending real-device validation.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/docs/QA_DEBT_REGISTER.md', '/docs/PHASE_6_INTEGRATION_POLISH_PLAN.md', '/src/components/dev/QADebtPanel.tsx', '/src/components/Diagnostics.tsx'],
    userVisiblePath: '/diagnostics',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['QA Debt Panel renders', 'Features dependent on HW remain PARTIALLY_VERIFIED'],
    verificationMethod: 'Automated + visual logic checks',
    verificationResult: 'Pass: Panel built and logic properly separated.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-39-visual-polish-a11y',
    phase: 6.1,
    name: 'Visual Refinements & Accessibility',
    description: 'Polished loading, fallback, and error states. Improved a11y with aria-labels and focus states. Maintained strict truth-labeling for swing metrics.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/src/components/AiCaddy.tsx', '/src/components/dev/QADebtPanel.tsx', '/docs/PHASE_6_INTEGRATION_POLISH_PLAN.md'],
    userVisiblePath: '/live',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['a11y states improved', 'Loading animations polished', 'QA Debt reads latest evidence', 'SwingReview preserves metric caveats'],
    verificationMethod: 'Automated build and manual code review',
    verificationResult: 'Pass: Live terminology misuse scrubbed, a11y added.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-40-tts-and-telemetry-polish',
    phase: 6.2,
    name: 'TTS and Telemetry Polish',
    description: 'Refactored duplicate TTS generation logic in AiCaddy to use the shared useTTS hook, and added latency warnings to the FrameHealthMeter for large payloads.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/src/components/AiCaddy.tsx', '/src/components/live/FrameHealthMeter.tsx'],
    userVisiblePath: '/live',
    backendEndpoints: ['/api/gemini/tts'],
    providerDependencies: ['Gemini TTS'],
    acceptanceCriteria: ['AiCaddy uses useTTS', 'FrameHealthMeter shows warnings'],
    verificationMethod: 'Automated test suites AiCaddy.voice.test.tsx and component visual spot checks',
    verificationResult: 'Partially Verified: Targeted unit tests passing for TTS isolation logic (VOICE-001 through 009) and typescript checks pass for FrameHealthMeter updates. Telemetry rendering is still IMPLEMENTED_UNVERIFIED and Needs manual testing.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-41-manual-qa-runner-evidence-capture',
    phase: 6.3,
    name: 'Manual QA Runner Evidence Capture Kit',
    description: 'In-app guided Manual QA Runner to record PASS/PARTIAL/FAIL evidence, capture notes, and export a JSON/Markdown QA receipt for real device/browser validation.',
    status: 'PARTIALLY_VERIFIED',
    filesTouched: ['/src/components/dev/ManualQARunner.tsx', '/src/lib/manualQaMatrix.ts', '/src/lib/manualQaReceipt.ts', '/docs/MANUAL_QA_EXECUTION_GUIDE.md', '/src/components/Diagnostics.tsx', '/src/components/dev/ManualQARunner.test.tsx'],
    userVisiblePath: '/diagnostics',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Manual QA Runner renders grouped gates', 'Status selection updates a gate', 'Notes update a gate', 'JSON export working', 'Markdown export working', 'Does not mutate ledger directly'],
    verificationMethod: 'Component tests for ManualQARunner metrics',
    verificationResult: 'Pass: Automated tests for ManualQARunner pass without failing. Manual tests by human tester requested.',
    knownBugs: [],
    fixHistory: [],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  },
  {
    featureId: 'f-42-runtime-hardening-pr1',
    phase: 6.6,
    name: 'Runtime Hardening PR 1',
    description: 'Add ErrorBoundaries, optimize LiveVideoInput with requestAnimationFrame, throttle FrameHealthMeter updates, and harden AudioContext usage.',
    status: 'IMPLEMENTED_UNVERIFIED',
    filesTouched: [
      '/src/components/live/LiveErrorBoundary.tsx',
      '/src/components/Caddy.tsx',
      '/src/live/liveFrameCapture.ts',
      '/src/hooks/useTTS.ts',
      '/src/components/live/FrameHealthMeter.tsx'
    ],
    userVisiblePath: 'N/A',
    backendEndpoints: [],
    providerDependencies: [],
    acceptanceCriteria: ['Passes unit tests for ErrorBoundary', 'Media cleanup improvements run without throwing'],
    verificationMethod: 'Automated Vitest suite',
    verificationResult: 'Pass automated tests, pending physical device',
    knownBugs: [],
    fixHistory: ['Moved FrameHealthMeter to throttled pulse', 'Reconfigured LiveVideoInput frame intervals to RAF', 'Added touch-target a11y classes to playback controls'],
    duplicateRiskNotes: 'None',
    lastUpdated: new Date().toISOString()
  }
];
